name: GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          username: uldyssian-sh
          show_icons: true
          theme: dark
          
      - name: Update README timestamp
        run: |
          echo "<!-- Updated: $(date) -->" >> README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update stats timestamp" || echo "No changes"
          git push || echo "Push failed"