name: Update GitHub Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday
  push:
    branches: [ main ]

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Update README with GitHub Stats
      uses: anmol098/waka-readme-stats@master
      with:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SHOW_PROJECTS: "False"
        SHOW_PROFILE_VIEWS: "True"
        SHOW_DAYS_OF_WEEK: "True"
        SHOW_LANGUAGE: "True"
        SHOW_OS: "True"
        SHOW_TIMEZONE: "True"
        SHOW_EDITORS: "True"
        SHOW_LANGUAGE_PER_REPO: "True"
        SHOW_SHORT_INFO: "True"
        SHOW_LOC_CHART: "True"
